#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# source ${HOME}/.profile (if present)
if [[ -s "${HOME}/.profile" ]]; then
  source "${HOME}/.profile"
fi

# Customize to your needs...
